server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # HTTP 健康检查端点
    location = /healthz {
        default_type text/plain;
        return 200 'ok';
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
